[platformio]
src_dir = Firmware/Source Code/HW2.x/DDS9959v2.2_Firmware

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Custom libraries shipped with the project
lib_extra_dirs = Libraries

; Build flags
build_flags =
    -Wno-unused-variable

; Serial monitor settings (match firmware)
monitor_speed = 115200
